services:
  beszel:
    image: henrygd/beszel:latest
    container_name: beszel
    restart: unless-stopped
    ports:
      - 4000:8090
    volumes:
      - /home/don/beszel_data:/beszel_data
      - ./beszel_socket:/beszel_socket

  beszel-agent:
    image: henrygd/beszel-agent:latest
    container_name: beszel-agent
    restart: unless-stopped
    network_mode: host
    volumes:
      - ./beszel_socket:/beszel_socket
      - /var/run/docker.sock:/var/run/docker.sock:ro
    environment:
      LISTEN: 45876
      # Do not remove quotes around the key
      KEY: "ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIDrXz0fFQwM2EvmUIiMjxr3Mc7vKcimUhrVyFp3J0klX"
