services:
  kavita:
    image: lscr.io/linuxserver/kavita:latest
    container_name: kavita
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Etc/UTC
      - DOTNET_SYSTEM_GLOBALIZATION_INVARIANT=true
    volumes:
      - /mnt/nvme/kavita/config:/config
      - /mnt/nvme/kavita/data:/data #optional
    ports:
      - 5000:5000
    restart: unless-stopped